output:
  downstreamListenerChannelArn:
    Fn::GetAtt: [ DownstreamListenerChannel, Arn ]

resources:
  Resources:
    DownstreamListenerChannel:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-${opt:stage}-downstream-listener-channel
    DownstreamListenerChannelBusPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          # Could also use Ref: DownstreamListenerChannel here.
          - Fn::GetAtt: [ DownstreamListenerChannel, QueueUrl ]
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action:
                - sqs:SendMessage
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Fn::GetAtt: [ DownstreamListenerChannelBusRule, Arn ]
              Resource:
                - Fn::GetAtt: [ DownstreamListenerChannel, Arn ]
    DownstreamListenerChannelBusRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: ${file(serverless/aws/event-bus.yml):output.eventBusName}
        EventPattern:
          detail-type:
            - prefix: 'test-entity'
        State: ENABLED
        Targets:
          - Id: DownstreamListenerChannel
            Arn:
              Fn::GetAtt: [ DownstreamListenerChannel, Arn ]
            InputPath: $.detail