output:
  notSoSecretName: ${self:service}/not-secret

iamRoleStatements:
  Effect: Allow
  Action:
    - secretsmanager:GetSecretValue
  Resource:
    Ref: NotSoSecret

resources:
  Resources:
    # Note...please don't do this...this is just for testing.
    # Use something like https://github.com/jgilbert01/serverless-secrets-mgr-plugin
    NotSoSecret:
      Type: 'AWS::SecretsManager::Secret'
      Properties:
        Name: ${self:service}/not-secret
        Description: This is a test secret.
        SecretString: "eyAibm90U2VjcmV0IjogImRlZmluaXRlbHkgbm90IHNlY3JldCIgfQ=="
